# Generated by Django 3.1.7 on 2021-08-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATH', '0004_auto_20210810_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_book',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_book',
            name='c_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_book',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_book',
            name='fuel',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_book',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_book',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
