# Generated by Django 3.1.7 on 2021-08-11 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATH', '0007_auto_20210810_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpdetail',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_book',
            name='pump',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PATH.pumpdetail'),
        ),
    ]
