# Generated by Django 3.1.7 on 2021-08-11 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATH', '0008_auto_20210811_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpdetail',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_book',
            name='pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PATH.pumpdetail'),
        ),
    ]
