# Generated by Django 3.1.7 on 2021-08-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATH', '0010_auto_20210811_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
    ]
