# Generated by Django 3.1.7 on 2021-08-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATH', '0011_pumpdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_book',
            name='pump',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
