# Generated by Django 3.1.7 on 2021-08-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATH', '0013_tbl_oilbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petrol', models.IntegerField(null=True)),
                ('deasel', models.IntegerField(null=True)),
            ],
        ),
    ]
