# Generated by Django 3.1.7 on 2021-08-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PATH', '0014_tbl_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_oilbook',
            old_name='oilfuel',
            new_name='oil',
        ),
    ]
