# Generated by Django 3.1.7 on 2021-08-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PATH', '0015_auto_20210816_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_count',
            old_name='deasel',
            new_name='diesel',
        ),
    ]
